version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "poc-parquearauco2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fi44kzo51jgh"
s3_prefix = "poc-parquearauco2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
